### ISSUE TITLE
can i add crypto available on coinmarketcap

### ISSUE THREAD

**Issue by massi1990** [matteodanelli/MMM-cryptocurrency#106]
Hello everyone,

I want to add one or more crypto that are available on coinmarketcap.

for example add the PKN.

thank you

**Comment by matteodanelli** [comment]
Added!
Just pull the latest version.

**Comment by lacalos** [comment]
hi. your module is fantastic, so i would like if add this coin or maybe how to add .
list:

-GENIE PROTOCOL
-4INT
-PARSIQ
-MITHAVERSE
-CIVILITATION
-LIQUIDUS
-ZENITH COIN (BLOCKCHAIN ZENITH)
-MANA
-HARMONY ONE
-HAPI
-EQIFI

thank you so much
