### ISSUE TITLE
Coins to be added (request purposes)

### ISSUE THREAD

**Issue by Neophilim** [matteodanelli/MMM-cryptocurrency#115]
Could you please add DAI. 

It is picking up quotes and viewing well, but the image placeholder is malfunctioning with "dai.png" (colored & black-white)
Also the name mysteriously is changing to "SAI"??

:) Thank you in advance!

**Comment by matteodanelli** [comment]
The right name for DAI is 'multi-collateral-dai'.
Since there are single and multi and coinmarketCap use the long name to identify that.
Just do a pull (I've added icons and updated the currency id) and use multi-collateral-dai inside the config ;)
