### ISSUE TITLE
Adding png for custom currency

### ISSUE THREAD

**Issue by xheer** [matteodanelli/MMM-cryptocurrency#119]
I am trying to add luna and Iadded a 50x50 png named luna.png to both the colored and black/white folder but when restarting magic mirror it still does not load the png.

**Comment by matteodanelli** [comment]
Have you added manually the currency inside the javascript file?
Which name have you used?

**Comment by xheer** [comment]
Thank you for replying and sorry for being such a noob lol.
I have added this to the config.js for magic mirror`

```
{
	module: "MMM-cryptocurrency",
	position: "bottom_right",
	config: {
		apikey: 'mykey',
		currency: ['ethereum', 'luna'],
		conversion: 'USD',
		headers: ['change24h'],
		displayType: 'logoWithChanges',
		showGraphs: false,
		maximumfractiondigits:3
	}
```

**Comment by matteodanelli** [comment]
It probably doesn't load even the data about luna because actually isn't included in the package.

You could do anyway. Just add inside MMM-cryptocurrency.js the following at line 75
`luna: 4172,` and then the coin will be available with the chart too.

**Comment by xheer** [comment]
Hmm... the data was accurately loading the LUNA -> USD value both before and after adding `luna: 4172,` at line 75. But the icon still wont load.

**Comment by matteodanelli** [comment]
Could you try to send me the icon you're using, so that I can check better which is the issue?

**Comment by xheer** [comment]
Yeah absolutely here it is
![luna](https://user-images.githubusercontent.com/83892518/166577118-867eb8a8-e95b-4965-9a1f-57816c0abef9.png)

**Comment by matteodanelli** [comment]
Ok, the issue wasn't the icon, but the naming. Coinmarketcap call that coin *terra-luna*.

I fixed with a commit, just update the module and you'll get it.
