### ISSUE TITLE
icon keep blinking

### ISSUE THREAD

**Issue by lilyangsta** [matteodanelli/MMM-cryptocurrency#14]
Hi there matteo, first of all i really thank you for what you've done and really appreciate this module of yours man seriously. By default you set var delay to 30000 and i know you said not to set it time less than 5 minutes, which is <300, so i put it at 400,500.....all the way to 1000 and the icons are still blinking haha By any chance, is there a reason why if you would know that my icon keep blinking?

**Comment by matteodanelli** [comment]
Hi, thank you.

Since value is computed in millisecond, you should set 300000, 400000, 500000 and so on.
A minute is equal to 60000.

Maybe the problem is there.

**Comment by lilyangsta** [comment]
ahhh millisecond....thanks for the clarification bro :D
