### ISSUE TITLE
price.style.fontSize = 'large' causing issues

### ISSUE THREAD

**Issue by iamtyce** [matteodanelli/MMM-cryptocurrency#17]
After the recent PR to change the `font-size` (see [here](https://github.com/matteodanelli/MMM-cryptocurrency/pull/13/files#diff-b18f9314b7bc89a8690d93bf65dbb411R244)) my MagicMirror setup has been showing very small fonts for each of the prices.

I've had to manually changed the line to be `price.style.fontSize = '30px'` in order to get the default large size back.

It could be nice to have this set to a default `px` value and maybe have a prop to override that if a user wants to?

**Comment by matteodanelli** [comment]
Yes, great idea. I'll update it later today.

**Comment by matteodanelli** [comment]
Sorry for the delay, but I fixed. I restored old version size and added a configuration in order to set manually font size. If this helps, I'll close the issue. Let me know!

**Comment by iamtyce** [comment]
Great work!
