### ISSUE TITLE
Mods: Reversed h/d/w, smaller font for logoWithChanges

### ISSUE THREAD

**Issue by jinjirosan** [matteodanelli/MMM-cryptocurrency#18]
Hi,
first off, love the module. Awesome stuff!
Couple feature requests which I've currently manually changed inthe MMM-cryptocurrency.js code:
- reversed the "changes" when used with logoWithChanges to better follow the graph (which shows the most recent value on the right. The changes line now shows the order 7d-24h-1h.
- For better proportions I've also changed the fontsize for the logoWithChanges to 'small'. Maybe you can make it a css var in a future version.

**Comment by matteodanelli** [comment]
Hi,
thank you for requests! If you want you can make directly a pull request towards me, so I can easily integrate into the library :)

**Comment by jinjirosan** [comment]
done :-)
