### ISSUE TITLE
IOTA graph not showing, significant digits only showing 2 not 5

### ISSUE THREAD

**Issue by jinjirosan** [matteodanelli/MMM-cryptocurrency#19]
Can't figure this one out. I'm using the latest version of the code and the options:

> 		{
> 			module: "MMM-cryptocurrency",
> 			position: "top_right",
> 			config: {
> 				currency: ['ethereum', 'ripple', 'bitcoin', 'iota'],
> 				conversion: 'EUR',
> 				displayLongNames: 'false',
> 				displayType: 'logoWithChanges',
> 				significantDigits: '5',
> 				showGraphs: 'true',
> 				headers: ['change24h', 'change1h', 'change7d'],
> 				fontSize: 'medium'
> 			}
> 		},

The graphs for Ethereum, Ripple and Bitcoin are showing but the graph for IOTA is not. In webpage source it shows empty instead of `<img src="https://files.coinmarketcap.com/generated/sparklines/1.png?cachePrevention=0.7866182075290848">`

Also the significantDigits setting of 5 are not showing anymore which did work in an older version.

**Comment by CriticalPoint** [comment]
How are you finding the SparkLine for a specific crypto? For arguments sake, Tronix (TRX)?

Looking at your link, the SparkLine has been generated and displays perfectly well at the link you've stipulated - https://files.coinmarketcap.com/generated/sparklines/1.png?cachePrevention=0.7866182075290848

**Comment by CriticalPoint** [comment]
So for you @jinjirosan , add this line;

https://pasteboard.co/H1P4FPJ.png

**Comment by matteodanelli** [comment]
Exactly. Just add them to your javascript file. I'll push an update with them later.

**Comment by matteodanelli** [comment]
Also, what do you mean significant digits are not more working? Which currency? 
Remember that prices are taken from coinmarketcap, which has its own approximation.

**Comment by jinjirosan** [comment]
@CriticalPoint awesome, that works. Thx!
@matteodanelli Ripple (XRP) for instance, it first showed 0.1745 and now it shows 1.99. it's a minor thing that it shows two decimals after the point, just wondering.

**Comment by matteodanelli** [comment]
Yes I got it, but unfortunately it's my source (coinmarketcap) which drops third and fourth decimal :)
