### ISSUE TITLE
Show percentage colors in detail view

### ISSUE THREAD

**Issue by lordvalium** [matteodanelli/MMM-cryptocurrency#21]
How could i show the colors of changes colored (red, green, white) in the detail view?

thx in advance

**Comment by CriticalPoint** [comment]
Mine shows this change, perhaps it's been updated already?

**Comment by matteodanelli** [comment]
They are set by default and they should be appear already. Which is your configuration?

**Comment by lordvalium** [comment]
No i am sorry, it is white on black. I dont mean "logoWithChanges" i mean the **detail** view :)

This is my config

`	modules: [
		{
			module: "MMM-cryptocurrency",
			position: "bottom_left",
			header: "",
			config: {
				currency: [
					"bitcoin",
					"ongsocial",
					"kyber-network",
					"qlink",
					"global-currency-reserve",
					"etherum-classic",
					"korecoin",
					"ubiq",
					"elastic",
					"spreadcoin"
				],
				headers: [
					"change24h",
					"change1h",
					"change7d"
				],
				displayType: "detail",
				showGraphs: true,
				fontSize: "x-large"
			}
		},`

**Comment by matteodanelli** [comment]
Oh I got it. I've implemented. Download latest commit and you'll get it.

**Comment by lordvalium** [comment]
Omg that is awesome matteo!  Thank you Very much !!!!!
