### ISSUE TITLE
typo in configuration displayTpe -> displayType

### ISSUE THREAD

**Issue by nerdmaennchen** [matteodanelli/MMM-cryptocurrency#22]
The above mentioned typo prevents the module from displaying in the right mode.
no graphs nor logos are drawn on a fresh install and since the configuration is called "displayTpe" and everywhere in the code "displayType" is tested agains it behaves as if the configuration is not set at all.

Btw.: You've made a super nice module for my mirror! Thank you so much for that.

Fix.:
just change line 9 in MMM-cryptocurrency.js to displayType: 'detail',

kind regards and all the best,
Lutz

**Comment by matteodanelli** [comment]
Oh.. Thanks you so much for have discovered this!

I fixed. Thank you!!!

**Comment by nerdmaennchen** [comment]
Wow, that was quick!

Thank you so much for fixing this and your awesome livetricker!
