### ISSUE TITLE
add cryptocurrency

### ISSUE THREAD

**Issue by chassain** [matteodanelli/MMM-cryptocurrency#24]
Hello,

Good work for this module.
I can display another crypto (OmiseGo) but there is no graph. How can I add money like airswap ?
Thanks.

**Comment by matteodanelli** [comment]
Hello, thanks!
So, I've added graph code for OmiseGo. Just update.

Then, there is a configuration called `limit` for the module. Set it to 200 and you should also see _airswap_. Let me know!

**Comment by chassain** [comment]
Perfect! Thanks a lot. Where can i find value for airswap's sparlineids cause i have no graph?...this module is great.

**Comment by matteodanelli** [comment]
Added also it. Try to update another time :)

**Comment by chassain** [comment]
Ok. I will try later. Thanks again.
