### ISSUE TITLE
Where do you find the correct logos to use?

### ISSUE THREAD

**Issue by E3V3A** [matteodanelli/MMM-cryptocurrency#26]
I want to add `zcash` (ZEC, `1437`).  
Where do you guys get/make the logos?

**Comment by matteodanelli** [comment]
Hi! You can logo around internet, for example here: [https://github.com/zcash/logos](url)

In order to add, you should fork repository and then create proper file into public folder.
At the moment, there is no chart too, so you should add also sparkline id into javascript file.

**Comment by CriticalPoint** [comment]
CoinMarketCap seems to be a good resource, since this module utilises it already

**Comment by E3V3A** [comment]
Here are their logos, but with apparently white background. 
```
https://coinmarketcap.com/static/public/sprites/all_views_market-cap-by-circulating-supply_0.png
https://files.coinmarketcap.com/static/img/coins/32x32/ethereum.png
https://files.coinmarketcap.com/static/img/coins/64x64/ethereum.png
https://files.coinmarketcap.com/static/img/coins/128x128/ethereum.png
```
@matteodanelli 
> ... then create proper file into public folder

What is a "proper" file? What file/image format etc, do you use?

**Comment by matteodanelli** [comment]
@E3V3A About proper file: there is a _public_ folder, which contains two subfolder, one for black/white logos and one for the coloured ones. Ideally, resolution should be 64*64, but you can use also 32*32 or more, since they'll be scaled.
Filename should be the one of the currency, so `zcash.png` in this case.

**Comment by matteodanelli** [comment]
As soon as I can, I'll download every icons of top 100 currencies, and I'll push an update. But if you have already do it, make a pull request :)
I'll add sparklines later today.
