### ISSUE TITLE
Get rid of redundant symbols in the detailed view

### ISSUE THREAD

**Issue by E3V3A** [matteodanelli/MMM-cryptocurrency#27]
Right now, when using `displayType`: *detail* view, there are too many redundant symbols shown.

- Percentages are shown in all change headers AND in the values themselves.
- The Euro symbol is shown in front of each currency value. 

This make it hard to read from a distance. 

1. How can I remove the `%` signs following the change values? 
2. How can I remove the Euro sign prefixing the price?
3. How can I put the Euro sign in the `Price` header instead, like this: `Price [€]`? 
4. How can I change the %-change header to: `%Δ (24h)` ?

**Comment by E3V3A** [comment]
- I managed to edit the `en.json` file to add the Eur and Delta symbols.
- I also managed to remove, the `%` from the change values, **but then the colors disappeared.**  :( 
- I did **not** manage to rid the Euro symbols.

Coloring seem to be RegEx'ing on `%` instead of value!

**Comment by matteodanelli** [comment]
Hi,

thanks for all your points. 
Your suggestions and comments are important to improve.

So, first, I colored values where there is percentage, and I remove percentage from the string since I need to evaluate a number. In your case, if you had removed percentage sign, you simply could drop if condition.
```
           if (this.config.headers.indexOf('change1h') > -1) {
                tdValues.push(currentCurrency.percent_change_1h)
            }
            if (this.config.headers.indexOf('change24h') > -1) {
                tdValues.push(currentCurrency.percent_change_24h)
            }
            if (this.config.headers.indexOf('change7d') > -1) {
                tdValues.push(currentCurrency.percent_change_7d)
            }

            for (var j = 0; j < tdValues.length; j++) {
                var tdWrapper = document.createElement('td')
                let currValue = tdValues[j]
                tdWrapper.style.color = this.colorizeChange(currValue)
                tdWrapper.innerHTML = currValue
                trWrapper.appendChild(tdWrapper)
            }
            wrapper.appendChild(trWrapper)
```

**Comment by E3V3A** [comment]
@matteodanelli  Super! I also managed to rid the `€` by adding the lines: 
```js
if (currValue.includes('€')) {
    currValue = currValue.replace("€","");
}
```
Then added a right justify to css file. Didn't bother to add any more css style class for the first column. 

```css
.mmm-cryptocurrency > tr {
    padding-bottom: 8px;
    text-align: right;
}
```
Now it look very nice!

![firefox_2018-01-24_15-19-59](https://user-images.githubusercontent.com/194392/35334195-2fcf8008-011a-11e8-87ef-88405cfff184.png)
