### ISSUE TITLE
updated module and it no longer works

### ISSUE THREAD

**Issue by Barobax** [matteodanelli/MMM-cryptocurrency#29]
ran git pull on the dir and restarted MagicMirror the module is no longer working. i had a backup reloaded and everything worked again.

**Comment by matteodanelli** [comment]
Hi, which is your configuration? I tested before push and it worked. I'm sorry to hear that.

**Comment by SpoturDeal** [comment]
Mine is not working as well, it doesn't even say loading/

**Comment by matteodanelli** [comment]
Are you on raspberry?

**Comment by SpoturDeal** [comment]
@matteodanelIi I am on Raspberry 3+

**Comment by matteodanelli** [comment]
Commit fixed version. Try now :)

**Comment by SpoturDeal** [comment]
@matteodanelli it is working again. Great Job.

Do you think it is possible to add the value of the owners wallet

```
wallet [
		 ['ripple', 300],
		 ['litecoin' ,17]
	  ],	
```

**Comment by Barobax** [comment]
ok sorry about the late response, i kept the default config and it seems like you guys figured it out without me, thanks everything is working again.
