### ISSUE TITLE
black and white vs color option

### ISSUE THREAD

**Issue by AdamMoses-GitHub** [matteodanelli/MMM-cryptocurrency#33]
I hacked the code to get this effect but you may want to add a config option to enable/disable to the colorization of the change, i.e. green for positive, red for negative. 

A lot of people like to keep the pure grayscale look on the mirror and that would go a long way to doing that. 

Also, including a + or - depending on the change, whether color or not would be helpful.

**Comment by matteodanelli** [comment]
Hi,
have you already done it? Don't forget to make a pull request, so I'll integrate this customisation! 👍
