### ISSUE TITLE
Graph not loading, only showing ".jpg" symbol

### ISSUE THREAD

**Issue by sobrien556** [matteodanelli/MMM-cryptocurrency#37]
Whenever I turn the graph option on, the graph doesn't load, it only shows the ".jpg" image symbol. Has anyone else had a problem with this?

**Comment by jinjirosan** [comment]
Yes, coinmarketcap changed the location where they put the sparklines (s2 vs files). I see that it is changed in the current MMM-cryptocurrency.js

**Comment by matteodanelli** [comment]
Hello, 
have you downloaded latest update?
It should be fixed! Let me know!

**Comment by sobrien556** [comment]
All good! Thank you!
