### ISSUE TITLE
Updates available for MMM-cryptocurrency module How to????

### ISSUE THREAD

**Issue by paddyhughes** [matteodanelli/MMM-cryptocurrency#39]
Hi 
Great Module thanks for all the hard work put into it.

Question I am getting a message saying updates available for the Module 
can you tell me how to up date it please.

**Comment by matteodanelli** [comment]
Hi, the simplest way is to download zip of the repository, then extract it and overwrite the MMM-cryptocurrency folder inside your MagicMirror project.

Else, if you are able to manage git repositories open your command-line and do `git pull`

Let me know if I helped.
