### ISSUE TITLE
New header config not optional

### ISSUE THREAD

**Issue by Klizzy** [matteodanelli/MMM-cryptocurrency#4]
I discovered that if i only specify one header ( headers: ['change24h'] ) it still displays the values from the apiResult.
In order to fix it we have to check how many headers are set and add the ones that are specified in the config. 

So one possible way would be that we add an check for the headers before the config arrays  are defined. Ideally we should now have only the headers from our config and add the values to the config arrays ```tableHeaderValues ``` and ```tdValues```

![bildschirmfoto 2017-05-21 um 23 30 00](https://cloud.githubusercontent.com/assets/15422170/26287515/800ec912-3e7d-11e7-97b7-a76d0c4c4478.png)

**Comment by matteodanelli** [comment]
Solved. Thanks for reporting.
