### ISSUE TITLE
Significant digits needs fixing

### ISSUE THREAD

**Issue by Rukahs** [matteodanelli/MMM-cryptocurrency#42]
Merge number 41that fixed the ability to have significant digits now shows too much detail or not enough detail depending on having crypto currencies of drastically different values. 
example: bitcoin currently has 7 significant figures to two decimal places, but ethereum and litecoin have 5 significant digits to two decimal places.
With the current commit, having enough digits to show the current value of bitcoin (to the penny) shows 10,000th's of a penny for litecoin.

**Comment by matteodanelli** [comment]
Well, you are right. 
In order to have different digits per currency I should implement an option for every currency.

Before this merge how it works? I can rollback to previous version in case.

**Comment by vinke1996** [comment]
@Rukahs I didn't think about that in first place.
@matteodanelli I have a option now that significantDigits is also an array. 
So for example currecy: ['bitcoin','litecoin','verge']
and the significantDigits : [4,3,6]
Let me know if this is something you can use.

**Comment by vinke1996** [comment]
I should put a pull request with the quick fix to put an array of singificantDigits. Maybe I can look later for the issue you said. Or maybe someone else?
