### ISSUE TITLE
Bitcoin not loading /showing

### ISSUE THREAD

**Issue by cisrev** [matteodanelli/MMM-cryptocurrency#58]
since the fall of the Bitcoin in March there is no info of value anymore (shows nothing) only the module. Seems the www page cannot load the info. Did something change maybe an apikey needed now or chnage to https??

**Comment by matteodanelli** [comment]
I've updated the module a couple of hours ago with updated API. Can you try and let me know if it's fixed? :)

**Comment by cisrev** [comment]
hej, cool thanks for your answer. Must i install the module completely new??
    Am Mittwoch, 11. März 2020, 23:23:35 MEZ hat Matteo <notifications@github.com> Folgendes geschrieben:  
 
 


I've updated the module a couple of hours ago with updated API. Can you try and let me know if it's fixed? :)

**Comment by matteodanelli** [comment]
Just do _git pull_ and restart. But you can reinstall from scratch if prefer.

**Comment by cisrev** [comment]
mille grazie :)

**Comment by cisrev** [comment]
i installed it new in modules but not working after restart 


git clone https://github.com/matteodanelli/MMM-cryptocurrency.git

**Comment by matteodanelli** [comment]
same error as before?

**Comment by cisrev** [comment]
ok, sorry i must update first all (npm etc.). Long time ago. see u later. But thankss for advice anyway.

**Comment by torth** [comment]
hey, I have the same problem and saw this new issue. Today I did git pull, npm install and restarted MM, but nothing changed. Still a view without data for configured currency

**Comment by torth** [comment]
update - I generated an apikey and configured this option, restart and now it's working. apikey is now a mandatory option?

**Comment by humdinger44** [comment]
I also have this issue. I did git pull, added apikey to my config, reboot, and it still does not work.

**Comment by matteodanelli** [comment]
Can you send me you configuration?

**Comment by humdinger44** [comment]
i pasted it in here then noticed i had typed "apiKey" after changing it to all lowercase it worked.

for others, this works for me:

		{
			module: "MMM-cryptocurrency",
			position: "bottom_left",
			config: {
				apikey :"my-secret-coinmarketcap-api",
				logoHeaderText: 'Crypto',
				currency: ['bitcoin','ethereum'],
				conversion: 'USD',
				headers: ['change7d'],
				displayType: 'detail',
				showGraphs: false,
				coloredLogos: false,
				showUSD: false,
				fontSize: "medium",
				}

**Comment by matteodanelli** [comment]
Great news!

**Comment by matteodanelli** [comment]
@torth  & @cisrev have you solved?

**Comment by cisrev** [comment]
hej, it works...my mistake..forgot the api key. thanks anyway...urgreat!!thank u very much
    Am Samstag, 14. März 2020, 10:29:46 MEZ hat Matteo <notifications@github.com> Folgendes geschrieben:  
 
 


@torth & @cisrev have you solved?

**Comment by cisrev** [comment]
superbe! Yes helped , all ok!!
