### ISSUE TITLE
Request:  Variable polling time

### ISSUE THREAD

**Issue by rstamand** [matteodanelli/MMM-cryptocurrency#61]
To limit API calls I would like to be able to set the polling time from 5 to 10 or 15 or 20 minute intervals, would this be possible to add?  Thanks, I love this module!

**Comment by matteodanelli** [comment]
Hello, it's not currently configurable, but you can edit the variable _delay_ inside **MMM-cryptocurrency.js** and change the value according to your preference. Remember that it means milliseconds, therefore 300000 equal to 5 minutes and so on..
