### ISSUE TITLE
FontSize

### ISSUE THREAD

**Issue by massi1990** [matteodanelli/MMM-cryptocurrency#66]
Hi

I set fontsize to medium but the display remains on xx-large

{
	module: "MMM-cryptocurrency",
	position: "top_right",
	config: {
		apikey: 'xxxxxxx-xxxxxx-xxxxxx-xxxxxx-xxxxxxxxxxxxxxxxx',
		currency: ['ethereum', 'bitcoin','xrp', 'dash', 'litecoin', 'iota', 'neo','xtz'],
		conversion: 'EUR',
		headers: ['change24h', 'change1h', 'change7d'],
		displayType: 'logoWithChanges',
		showGraphs: true,
		fontSize: medium,
	}
}

**Comment by matteodanelli** [comment]
Try to place it rounded by the character ', like `fontSize: 'medium',`

**Comment by massi1990** [comment]
does not work

**Comment by matteodanelli** [comment]
Same font size, even after reload?
