### ISSUE TITLE
Charts do not update

### ISSUE THREAD

**Issue by SvenSommer** [matteodanelli/MMM-cryptocurrency#68]
Hey since nearly a week the graphs do not get any updates
![sparklines](https://user-images.githubusercontent.com/10847488/96352061-c16f6380-10c0-11eb-8bff-b6c63a4efa1a.png)
I had a look into the implementation of those.
` graph.src = 'https://s2.coinmarketcap.com/generated/sparklines/web/7d/usd/' + this.sparklineIds[apiResult[j].slug] + '.png?cachePrevention=' + Math.random()`
I couldn't find any hint in the official implementation of those sparklines in the official api of coinmarketcap.
https://coinmarketcap.com/api/documentation/v1/#section/Introduction

Any tips on how to fix this?

**Comment by vladeta** [comment]
I have the same issue from 2 days ago...
Any help?

**Comment by matteodanelli** [comment]
I'll check tonight. That's not officially documented. Maybe they suddenly changed the endpoint or some parameters. 
I'll fix asap.

**Comment by matteodanelli** [comment]
ok @vladeta @SvenSommer .
I fixed. Try to see if it has been solved. Just do a git pull of the module and refresh the mirror.

Let me know!

**Comment by olexs** [comment]
Perfect timing - I've been seeing this issue the past few days on my mirror, decided to finally look into it today. Can confirm the update fixes it. 

Also, not sure if it's just me used to the straight line or do the fixed "s3" sparklines look more detailed than the old ones to anyone else?

**Comment by matteodanelli** [comment]
@olexs Yes, it seems so. I'm not sure but I think they incremented the number of points stored. Not a bad thing after all :)

**Comment by SvenSommer** [comment]
Thanks for fixing. Lightning fast ;)

**Comment by vladeta** [comment]
Works like a charm! Thanks for such a quick fix!
