### ISSUE TITLE
Add API Call delay, getting data from CoinMarketCap, to the Config section.

### ISSUE THREAD

**Issue by Macster999** [matteodanelli/MMM-cryptocurrency#70]
Hi,
I am going over my limit in API calls to CoinMarketCap, and it would be nice to set it in config instead of modifying the code directly.
Thanks for writing this module
Cheers,
Michel

**Comment by matteodanelli** [comment]
Hey,
your request is about to have the delay as an option right?
If yes, it's possible. Let me know and I'll do it soon.

**Comment by jimmysmallse3** [comment]
I'm running into the same issue. Everyday I was receiving an email saying I'd hit my daily cap and then yesterday I got an email saying I hit my monthly cap so the price stopped updating on my MagicMirror. If we could set that in the config that would be great. Awesome module by the way, keep it up!

**Comment by matteodanelli** [comment]
Done, update the module and pass the *apiDelay* parameter, set as seconds.

**Comment by djtale** [comment]
Hello @matteodanelli ,

Regarding the apiDelay, I'm wondering how it behaves when I used multiple pages.
On my Magic Mirror, I have your module on 1 page (over 7 pages). And I'm switching automatically the pages every minute.
I have setup the apiDelay to 3600 (seconds if I'm right). So every 7 minutes I display the module.

My question is : everytime I display the page with the module, is there a call to the api ?

Thanks

**Comment by matteodanelli** [comment]
Honestly, I don't know. When I have a couple of second I'll try to verify it.
If you want to check yourself with your configuration, just open ChromeDevTools and see how many times CoinMarket api is called.
