### ISSUE TITLE
New cryptocurrency

### ISSUE THREAD

**Issue by FelixGryson** [matteodanelli/MMM-cryptocurrency#73]
Hello

Nice module!
I already managed to show on screen a new cc (not listed in your description).
But on the 2nd one - polkadot - nothing is showing. I wrote its name in differen ways, but noway to show.
Is it possible to have Polkadot (DOT) on screen?

BR

**Comment by matteodanelli** [comment]
Hello, are you able to display the value while the chart is missing or both cannot be visible?

**Comment by FelixGryson** [comment]
Hello

Nothing is visible from Polkadot.
No logo, no value, no chart.

**Comment by matteodanelli** [comment]
Ok, let me check tomorrow. I'll try to update the library adding it.
I'll let you know soon!

**Comment by FelixGryson** [comment]
Thx a lot. Is not urgent :)

**Comment by matteodanelli** [comment]
Done, the name is "polkadot-new".

It seems strange but it's the marketcap naming.
Just update to latest versione and you have it!

**Comment by FelixGryson** [comment]
Works! Thanks a lot!
