### ISSUE TITLE
The Graph (GRT) addition to list

### ISSUE THREAD

**Issue by buraknroll-1** [matteodanelli/MMM-cryptocurrency#74]
Hi,
Very nice addition..
Can we add GRT (The Graph) to the list?

Thanks

**Comment by matteodanelli** [comment]
Yes, added.
Update to latest versione and config as "the graph".

**Comment by Tippon** [comment]
> Yes, added.
> Update to latest versione and config as "the graph".

Hi :)

Sorry to add to a closed issue, but using 'the graph' currently doesn't work. I've got it working by using 'the-graph', taken from Coin Market Cap's address bar.

Thanks :)

**Comment by matteodanelli** [comment]
Right, nice to have reminded that. Sorry for the mistake!
