### ISSUE TITLE
logoWithChanges show only 1d%

### ISSUE THREAD

**Issue by BiggyOC** [matteodanelli/MMM-cryptocurrency#84]
Hey there!

First of all thank you for the awesome extension.
Is there a possibility to reduce the shown percentages to only show the daily change?

Kind regards BiggyOC

**Comment by matteodanelli** [comment]
Hi, 
Thanks!
Have you tried with `headers : "change24h"` ?

**Comment by BiggyOC** [comment]
Hi matteo,
yes I did, thats my config:

{		
	module: "MMM-cryptocurrency",
	position: "top_left",
	config: {
		  apikey: 'xxxx',
		  currency: ['bitcoin', 'ethereum'],
		  logoHeaderText: 'Cryptowährungen',
		  conversion: 'EUR',
		  minimumFractionDigits: 2,
		  maximumFractionDigits: 2,
		  headers: ['change24h'],
		  displayType: 'logoWithChanges',
		  showGraphs: true
	  }
}

This is the output:
![image](https://user-images.githubusercontent.com/64696787/115235444-7a6b3500-a11a-11eb-8e0f-d2c491e0e2f0.png)

**Comment by matteodanelli** [comment]
Oh yes, I understood what you need. At the moment, it's not implemented.
I'll try to do it, or feel free to contribute and open a request ;)
