### ISSUE TITLE
What am I doing wrong here?

### ISSUE THREAD

**Issue by SaintelDaily** [matteodanelli/MMM-cryptocurrency#86]
I cant seem to get this to work. What am I doing wrong? 

 {
	module: "MMM-cryptocurrency",
	position: "top_right",
	config: {
		apikey: 'XXXXX Hidden for Privacy XXXXX',
	currency: [‘bitcoin’, 'ethereum', ‘ethereum-classic’, ‘xrp’, ‘cardano’],
		conversion: ‘USD’,
		headers: ['change24h', 'change1h', 'change7d'],
		displayType: 'logoWithChanges',
		showGraphs: true, 
	}
},

**Comment by branttaylor** [comment]
Same issue here. I went even simpler with my config just to try and get it working and it's just blank. I only see "Currency" and "Price" with a line underneath, nothing else.

```
{
                module: "MMM-cryptocurrency",
                position: "top_left",
                config: {
                        apiKey: 'redacted'
                }
}
```

**Comment by SaintelDaily** [comment]
I just switched to JAST. It does stocks and crypto without a need for API. only downside it does not have all the crypto out there since it uses Yahoo. PRO -Tip when entering crypt, the symbol has to be in this format "BTC-USD"  

https://github.com/jalibu/MMM-Jast

**Comment by matteodanelli** [comment]
Can you please tell me the MagicMirror version you are using?
I've just tested both your configurations and they work.
@branttaylor @SaintelDaily 
Do you see any errors in console?
Can you see other modules?

**Comment by lacalos** [comment]
hi mr matteodanelli, i can writing you for a new module amazing with crypto?
