### ISSUE TITLE
Coins have broken logos, missing graphs

### ISSUE THREAD

**Issue by MichaelNino** [matteodanelli/MMM-cryptocurrency#89]
So far, Polygon, Chainlink, Cosmos are broken images-- missing graphs too.

![Screenshot from 2021-07-03 12-45-44](https://user-images.githubusercontent.com/54298352/124361354-c0557680-dbfc-11eb-9d8e-aa741b1d0cd6.png)

**Comment by matteodanelli** [comment]
Thanks for have reported the issue! I'm looking to that!

**Comment by matteodanelli** [comment]
About logo, those currencies haven't the logo yet supported. I'll place it with the next update.

**Comment by MichaelNino** [comment]
The graphs are also missing

On 2021-07-03 15:40, Matteo wrote:

> About logo, those currencies haven't the logo yet supported. I'll place 
> it with the next update.
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].


Links:
------
[1] 
https://github.com/matteodanelli/MMM-cryptocurrency/issues/89#issuecomment-873460193
[2]

**Comment by matteodanelli** [comment]
Fully supported in the latest release, just update the module ;)
