### ISSUE TITLE
Currency not showing, only Header

### ISSUE THREAD

**Issue by TweetPete** [matteodanelli/MMM-cryptocurrency#9]
Hi, I wanted to try the module on my raspberry pi zero, but I have the issue that the currency and the price isn't showing. The header is displayed correctly and changes accordingly to the settings. I tried the proposed example and other settings.

**Comment by matteodanelli** [comment]
Hi @TweetPete , have you solved?

**Comment by TweetPete** [comment]
Yes thank you. I thank tried again without any conf settings and from there on it worked. Guess I had a typo somewhere. BTW: does the order of the config settings matter ? 
Best regards
