### ISSUE TITLE
Change4h

### ISSUE THREAD

**Issue by massi1990** [matteodanelli/MMM-cryptocurrency#90]
hello,

I like add change in 4h, can you confirm this command ?

if (this.config.headers.indexOf('change4h') > -1) {
            tableHeaderValues.push(this.translate('CHANGE') + ' (4h)')

**Comment by matteodanelli** [comment]
What's your goal? I didn't get it.

**Comment by massi1990** [comment]
I would like to have the change of 4 hours instead of 1 hour

**Comment by matteodanelli** [comment]
Unfortunately, coinmarketcap doesn't provide directly that value, so you cannot simply update the header and compute the value. It's not easily feasible at the moment.
