### ISSUE TITLE
Module is causing css issues with MM core and other modules

### ISSUE THREAD

**Issue by jalibu** [matteodanelli/MMM-cryptocurrency#92]
Hi,
a user opened an issue for one of my modules and complained about some unpretty list alignments. After some debugging, we found out that the reason was in this module's
 `MMM-cryptocurrency.css`.

The following css selector matches to *all* spans.
```
.mmm-cryptocurrency-icon > tr > td > img, span{
    vertical-align: middle;
}
```

**Comment by jalibu** [comment]
probably that's what you want:
```
.mmm-cryptocurrency-icon > tr > td {
  img, span {
     vertical-align: middle;
  }
}
```

**Comment by matteodanelli** [comment]
Updated! Thanks for the debug!
