### ISSUE TITLE
No Information Appearing

### ISSUE THREAD

**Issue by bzoit** [matteodanelli/MMM-cryptocurrency#99]
Hello everyone! When I setup the cryptocurrency module, only the top bar saying "Cryptocurrency" is appearing. The logo nor the price shows up. If anyone can help, that'd be very appreciated!

Config.js: pastebin.com/MPbD9kpW
![image](https://user-images.githubusercontent.com/71105100/141886288-c341adb5-5a21-4fa1-ad19-ffe51eaabffb.jpeg)

**Comment by matteodanelli** [comment]
Can you try to add `currency: ['bitcoin']` to the config?

**Comment by bzoit** [comment]
I think the cryptocurrency modules is what's causing this problem. When I uninstall it everything works fine. This is the logs from when I run the MagicMirror with the cryptocurrency module installed: pastebin.com/fvryjRyW

**Comment by matteodanelli** [comment]
Could be related to this? https://github.com/matteodanelli/MMM-cryptocurrency/issues/100#issue-1056458044

**Comment by bzoit** [comment]
> Could be related to this? https://github.com/matteodanelli/MMM-cryptocurrency/issues/86#issuecomment-950281067

That fixed it.
